<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-7HB0GS3K" ignored="0" name="Default test" tests="1" failures="1" timestamp="27 Mar 2020 19:58:38 GMT" time="17.587" errors="0">
  <testcase name="doValidUserNameValidPasswordLogin" time="2.556" classname="tests.LoginPageTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [his should be working, but something&amp;apos;s gone wrong. Please try again soon. [500.GENERIC]] but found [This should be working, but something&amp;apos;s gone wrong. Please try again soon. [500.GENERIC]]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [his should be working, but something's gone wrong. Please try again soon. [500.GENERIC]] but found [This should be working, but something's gone wrong. Please try again soon. [500.GENERIC]]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at tests.LoginPageTests.doValidUserNameValidPasswordLogin(LoginPageTests.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- doValidUserNameValidPasswordLogin -->
</testsuite> <!-- Default test -->
